version: '3'
services:
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=phuc_bridge
      - MONGO_PASSWORD=mypassword
      - REDIS_SECRET=secret
    command: npm run dev